Some config items are taken from https://raw.githubusercontent.com/jamiecollinson/dotfiles/master/config.org

* Setup
** Configure package sources
Add MELPA as a package repository.

#+BEGIN_SRC emacs-lisp
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)
#+END_SRC

** Bootstrap use-package
If =use-package= is not installed, install it

#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
    (package-install 'use-package))
  (setq use-package-verbose t)
  (require 'use-package)
  (setq load-prefer-newer t)
#+END_SRC





All packages should be installed via the package manager. 
This is equivalent to setting =:ensure t= on each call to =use-package=

#+BEGIN_SRC emacs-lisp
  (setq use-package-always-ensure t)
#+END_SRC

** Make it easy to find and edit this file via "C-c I"
#+BEGIN_SRC emacs-lisp
  (defun find-config ()
    "Edit config.org"
    (interactive)
    (find-file "~/config/emacs/config.org"))

  (global-set-key (kbd "C-c I") 'find-config)
#+END_SRC

** Set custom settings to load in own file

Stop emacs from adding settings to init.el by making the customize-file a temporary file

#+BEGIN_SRC emacs-lisp
  (setq custom-file (make-temp-file "emacs-custom"))
#+END_SRC
* Preferences
** Don't display the help screen on startup

#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-screen t)
#+END_SRC

** Turn off unwanted window decorations

#+BEGIN_SRC emacs-lisp
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (menu-bar-mode -1)
#+END_SRC

** Disable the error bell

#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function 'ignore)
#+END_SRC

** Make the =yes or no= prompts shorter.

#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

** Backup file creation options

Move all backup files into a common central location

#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist '(("." . "~/.emacs.d/backup"))
        backup-by-copying t    ; Don't delink hardlinks
        version-control t      ; Use version numbers on backups
        delete-old-versions t  ; Automatically delete excess backups
        kept-new-versions 20   ; how many of the newest versions to keep
        kept-old-versions 5    ; and how many of the old
        )
#+END_SRC
** Start in Fullscreen
#+BEGIN_SRC emacs-lisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
(add-to-list 'default-frame-alist '(font . "Consolas"))
(set-face-attribute 'default t :font "Consolas")
#+END_SRC
** Don't use tabs
#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
#+END_SRC

** Performance Tweaks
#+BEGIN_SRC emacs-lisp
(defun my-minibuffer-setup-hook ()
  (setq gc-cons-threshold most-positive-fixnum))

(defun my-minibuffer-exit-hook ()
  (setq gc-cons-threshold 800000))

(add-hook 'minibuffer-setup-hook #'my-minibuffer-setup-hook)
(add-hook 'minibuffer-exit-hook #'my-minibuffer-exit-hook)

#+END_SRC

* Interface
** Command completion

Use =ivy= as a completion framework for the minibuffer.

#+BEGIN_SRC emacs-lisp
  (use-package ivy
      :diminish ivy-mode
      :config
      (ivy-mode t))
#+END_SRC

Disable ivy default filter start.

#+BEGIN_SRC emacs-lisp
  (setq ivy-initial-inputs-alist nil)
#+END_SRC

** Better searching

Use ag for searches
#+BEGIN_SRC emacs-lisp
  (use-package ag)
#+END_SRC

Use swiper to improve on =isearch=
#+BEGIN_SRC emacs-lisp
  (use-package swiper
    :config
    (global-set-key "\C-s" 'swiper))
#+END_SRC

Use counsel-ag for fast grep inside a project
#+BEGIN_SRC emacs-lisp
  (use-package counsel
    :config
    (counsel-mode)
    (global-set-key (kbd "C-c k") 'counsel-ag))
  (use-package counsel-etags
    :ensure t
    :bind (("C-]" . counsel-etags-find-tag-at-point))
    :init
    (add-hook 'prog-mode-hook
          (lambda ()
            (add-hook 'after-save-hook
              'counsel-etags-virtual-update-tags 'append 'local)))
    :config
    (setq counsel-etags-update-interval 60)
    (setq counsel-etags-tags-program "D:\\\\home\\\\ctags.exe")
    (add-to-list 'counsel-etags-ignore-directories "build"))
#+END_SRC

Use avy for characteavr based searches in a file.
#+BEGIN_SRC emacs-lisp
  (use-package ace-jump-mode
    :config  
    :bind("M-s" . 'ace-jump-mode))
#+END_SRC

** Dired mode

Use =dired-rainbow= for more colors in dired buffers.
=dired-hacks-utils= is a common set of functions for dired-enhancing tools.
=dired-collaps= collapses folders together that only contain more subfolders.

#+BEGIN_SRC emacs-lisp
  (setq dired-dwim-target t)
  (use-package dired-rainbow)
  (use-package dired-hacks-utils)  
#+END_SRC
** Buffer handling


Use =ibuffer= as a default to show buffers and also open it in another window
#+BEGIN_SRC emacs-lisp
  (defalias 'list-buffers 'ibuffer)
  
  ;; nearly all of this is the default layout
  (setq ibuffer-formats 
        '((mark modified read-only " "
                (name 60 60 :left :elide) ; change: 30s were originally 18s
                " "
                (size 9 -1 :right)
                " "
                (mode 16 16 :left :elide)
                " " filename-and-process)
          (mark " "
                (name 16 -1)
                " " filename)))
  (use-package ibuffer-projectile)
#+END_SRC

** Treemacs

#+BEGIN_SRC emacs-lisp
(use-package treemacs
  :ensure t
  :defer t
  :init
  (with-eval-after-load 'winum
    (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
  :config
  (progn
    (setq treemacs-collapse-dirs                 (if (executable-find "python") 3 0)
          treemacs-deferred-git-apply-delay      0.5
          treemacs-display-in-side-window        t
          treemacs-file-event-delay              5000
          treemacs-file-follow-delay             0.2
          treemacs-follow-after-init             t
          treemacs-git-command-pipe              ""
          treemacs-goto-tag-strategy             'refetch-index
          treemacs-indentation                   2
          treemacs-indentation-string            " "
          treemacs-is-never-other-window         nil
          treemacs-max-git-entries               5000
          treemacs-no-png-images                 nil
          treemacs-no-delete-other-windows       t
          treemacs-project-follow-cleanup        nil
          treemacs-persist-file                  (expand-file-name ".cache/treemacs-persist" user-emacs-directory)
          treemacs-recenter-distance             0.1
          treemacs-recenter-after-file-follow    nil
          treemacs-recenter-after-tag-follow     nil
          treemacs-recenter-after-project-jump   'always
          treemacs-recenter-after-project-expand 'on-distance
          treemacs-show-cursor                   nil
          treemacs-show-hidden-files             t
          treemacs-silent-filewatch              nil
          treemacs-silent-refresh                nil
          treemacs-sorting                       'alphabetic-desc
          treemacs-space-between-root-nodes      t
          treemacs-tag-follow-cleanup            t
          treemacs-tag-follow-delay              1.5
          treemacs-width                         35)

    ;; The default width and height of the icons is 22 pixels. If you are
    ;; using a Hi-DPI display, uncomment this to double the icon size.
    ;;(treemacs-resize-icons 44)

    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)
    (treemacs-fringe-indicator-mode t)
    (pcase (cons (not (null (executable-find "git")))
                 (not (null (executable-find "python3"))))
      (`(t . t)
       (treemacs-git-mode 'deferred))
      (`(t . _)
       (treemacs-git-mode 'simple))))
  :bind
  (:map global-map
        ("M-0"       . treemacs-select-window)
        ("C-x t 1"   . treemacs-delete-other-windows)
        ("C-x t t"   . treemacs)
        ("C-x t B"   . treemacs-bookmark)
        ("C-x t C-t" . treemacs-find-file)
        ("C-x t M-t" . treemacs-find-tag)))


(use-package treemacs-projectile
  :after treemacs projectile
  :ensure t)

(use-package treemacs-icons-dired
  :after treemacs dired
  :ensure t
  :config (treemacs-icons-dired-mode))

(use-package treemacs-magit
  :after treemacs magit
  :ensure t)
#+END_SRC
* Appearance

Use the material color theme

#+BEGIN_SRC emacs-lisp
  (use-package material-theme
    :config
    (load-theme 'material t))
#+END_SRC

Highlight the current line.

#+BEGIN_SRC emacs-lisp
  (global-hl-line-mode 1)
#+END_SRC

Show line numbers

#+BEGIN_SRC emacs-lisp
  (global-display-line-numbers-mode 1)
#+END_SRC

Leerzeichen mode shows tabs, spaces and newlines

#+BEGIN_SRC emacs-lisp
  (use-package leerzeichen
    :config
    (leerzeichen-mode))
#+END_SRC

Set the font size.
#+BEGIN_SRC emacs-lisp
(set-face-attribute 'default nil :height 120)
#+END_SRC

* Coding
** Programming specific interface improvements

Highlight parens etc. for improved readability.

#+BEGIN_SRC emacs-lisp
  (use-package rainbow-delimiters
    :config
    (add-hook 'prog-mode-hook 'rainbow-delimiters-mode))
#+END_SRC

Highlight strings which represent colours. I only want this in programming modes, and I don't want colour names to be highlighted (=x-colors=).

#+BEGIN_SRC emacs-lisp
  (use-package rainbow-mode
    :config
    (setq rainbow-x-colors nil)
    (add-hook 'prog-mode-hook 'rainbow-mode))
#+END_SRC

Keep things indented correctly.

#+BEGIN_SRC emacs-lisp
  (use-package aggressive-indent)
  (setq tab-width 4)
  (setq-default tab-width 4)
#+END_SRC

Smart dash guesses _ vs - depending on context.

#+BEGIN_SRC emacs-lisp
  (use-package smart-dash
    :config
    (add-hook 'python-mode-hook 'smart-dash-mode))
#+END_SRC

** Project management

Projectile handles folders which are in version control.

#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :config
    (projectile-mode)
    (setq projectile-indexing-method 'alien)
    )
#+END_SRC

Tell projectile to integrate with =ivy= for completion.

#+BEGIN_SRC emacs-lisp
  (setq projectile-completion-system 'ivy)
#+END_SRC

Enable caching for large files

#+BEGIN_SRC emacs-lisp
  (setq projectile-enable-caching t)
#+END_SRC

Set Keybinding for finding files in a project and switching between related files
(for example .h/.cpp files)

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-o") 'projectile-find-file)
  (global-set-key (kbd "M-O") 'projectile-find-file-in-known-projects)
  (global-set-key (kbd "C-c o") 'projectile-find-other-file)
  (global-set-key (kbd "C-c p c") 'projectile-compile-project)
  (global-set-key (kbd "C-c p d") 'projectile-dired)
  (global-set-key (kbd "C-c p r") 'projectile-run-project)
  (global-set-key (kbd "C-c p t") 'projectile-test-project)
#+END_SRC

** Git
Use magit as a frontend for git. =C-x g= to open it.

#+BEGIN_SRC emacs-lisp
  (use-package magit
    :bind ("C-x g" . magit-status))
#+END_SRC

TimeMachine lets us step through the history of a file as recorded in git.

#+BEGIN_SRC emacs-lisp
  (use-package git-timemachine)
#+END_SRC

** Syntax checking
=Flycheck= is a general syntax highlighting framework which other packages hook into. It's an improvment on the built in =flymake=.

#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :config
    (add-hook 'after-init-hook 'global-flycheck-mode)
    (setq-default flycheck-highlighting-mode 'lines)
    ;; Define fringe indicator / warning levels
    (define-fringe-bitmap 'flycheck-fringe-bitmap-ball
      (vector #b00000000
              #b00000000
              #b00000000
              #b00000000
              #b00000000
              #b00000000
              #b00000000
              #b00011100
              #b00111110
              #b00111110
              #b00111110
              #b00011100
              #b00000000
              #b00000000
              #b00000000
              #b00000000
              #b00000000))
    (flycheck-define-error-level 'error
      :severity 2
      :overlay-category 'flycheck-error-overlay
      :fringe-bitmap 'flycheck-fringe-bitmap-ball
      :fringe-face 'flycheck-fringe-error)
    (flycheck-define-error-level 'warning
      :severity 1
      :overlay-category 'flycheck-warning-overlay
      :fringe-bitmap 'flycheck-fringe-bitmap-ball
      :fringe-face 'flycheck-fringe-warning)
    (flycheck-define-error-level 'info
      :severity 0
      :overlay-category 'flycheck-info-overlay
      :fringe-bitmap 'flycheck-fringe-bitmap-ball
      :fringe-face 'flycheck-fringe-info))
(eval-after-load 'flycheck
  '(add-hook 'flycheck-mode-hook #'flycheck-clang-tidy-setup))
    #+END_SRC

** Autocomplete

Company mode provides good autocomplete options.

#+BEGIN_SRC emacs-lisp
  (use-package company
    :diminish
    :config
    (add-hook 'after-init-hook 'global-company-mode)
    (global-set-key (kbd "C-<tab>") 'company-complete)
    (setq company-idle-delay 0.5))

#+END_SRC

Remove default company backends -> We only want the ones we need and we configure them with their related packages
But we keep dabbrev as we want to complete based on words inside the buffer.
#+BEGIN_SRC emacs-lisp
  (setq company-backends nil)
  (add-to-list 'company-backends 'company-dabbrev)
  (setq company-dabbrev-downcase nil)
  (use-package company-lsp
    :requires company
    :config
    (push 'company-lsp company-backends)
     ;; Disable client-side cache because the LSP server does a better job.
    (setq company-transformers nil
        company-lsp-async t
        company-lsp-cache-candidates nil))
#+END_SRC
** Snippets

Use yasnippet for test-snippets and their completion when pressing =TAB=

#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :diminish yas-minor-mode
    :config
    (add-to-list 'yas-snippet-dirs "~/.emacs.d/yasnippet-snippets")
    (add-to-list 'yas-snippet-dirs "~/.emacs.d/snippets")
    (add-to-list 'yas-snippet-dirs "~/config/snippets")
    (yas-global-mode)
    (global-set-key (kbd "M-/") 'company-yasnippet)

    ;; Add yasnippet support for all company backends
    ;; https://github.com/syl20bnr/spacemacs/pull/179
    (defvar company-mode/enable-yas ;TODO: 
      "Enable yasnippet for all backends.")

    (defun company-mode/backend-with-yas (backend)
      (if (or (not company-mode/enable-yas) (and (listp backend) (member 'company-yasnippet backend)))
          backend
        (append (if (consp backend) backend (list backend))
                '(:with company-yasnippet))))

    (setq company-backends (mapcar #'company-mode/backend-with-yas company-backends))
    )
#+END_SRC
** Markdown

#+BEGIN_SRC emacs-lisp
  (use-package markdown-mode
    :commands (markdown-mode gfm-mode)
    :mode (("README\\.md\\'" . gfm-mode)
           ("\\.md\\'" . markdown-mode)
           ("\\.markdown\\'" . markdown-mode))
    :init (setq markdown-command "multimarkdown"))
#+END_SRC
** C

Open .h files in c++-mode

#+BEGIN_SRC emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
#+END_SRC

Indent with width 4 and use clang formatting for auto-formatting on save

#+BEGIN_SRC emacs-lisp
  (use-package clang-format
    :config
    (defun my-formatting-setup()
      (global-set-key (kbd "C-c l") 'clang-format-buffer)
      (setq-default tab-width 4)
      (setq tab-width 4)
      (setq c-basic-offset 4))

    (add-hook 'c-mode-hook #'my-formatting-setup)
    (add-hook 'c++-mode-hook #'my-formatting-setup)
    (add-hook 'c++-mode-hook
            (lambda () (add-hook 'before-save-hook 'clang-format-buffer nil 'local))))
#+END_SRC

** Indexing
RTags (commented out to check check out clangd and lsp-mode instead)
#+BEGIN_SRC emacs-lisp
  ;; (use-package rtags
  ;;   :config 
  ;;   (define-key c-mode-base-map (kbd "M-.")
  ;;     (function rtags-find-symbol-at-point))
  ;;   (define-key c-mode-base-map (kbd "M-,")
  ;;     (function rtags-find-references-at-point))
  ;;   (define-key c-mode-base-map (kbd "M-#")
  ;;     (function rtags-find-symbol-current-file))
  ;;   (rtags-enable-standard-keybindings)
  ;;   (setq rtags-autostart-diagnostics t)
  ;;   (rtags-diagnostics)
  ;;   (setq rtags-display-result-backend 'ivy)

  ;;   (global-set-key (kbd "<M-up>") 'rtags-previous-match)
  ;;   (global-set-key (kbd "<M-down>") 'rtags-next-match)
  ;;   (global-set-key (kbd "<M-left>") 'rtags-location-stack-back)
  ;;   (global-set-key (kbd "<M-right>") 'rtags-location-stack-forward))

  ;; (use-package company-rtags
  ;;   :config
  ;;   (add-to-list 'company-backends 'company-rtags))

  ;; (use-package flycheck-rtags
  ;;   :config
  ;;   (defun my-flycheck-rtags-setup ()
  ;;     (flycheck-select-checker 'rtags)
  ;;     (setq-local flycheck-highlighting-mode nil) ;; RTags creates more accurate overlays.
  ;;     (setq-local flycheck-check-syntax-automatically nil))
  ;;   (add-hook 'c-mode-hook #'my-flycheck-rtags-setup)
  ;;   (add-hook 'c++-mode-hook #'my-flycheck-rtags-setup)
  ;;   (add-hook 'objc-mode-hook #'my-flycheck-rtags-setup))

#+END_SRC

clangd + lsp-mode
#+BEGIN_SRC emacs-lisp
    (use-package lsp-mode
      :config
      (setq lsp-clients-clangd-args '("-j=4" "-background-index" "-log=error"))
      (setq lsp-prefer-flymake nil) ;; Prefer using lsp-ui (flycheck) over flymake.
      (add-hook 'c++-mode-hook #'lsp)
      (add-hook 'python-mode-hook #'lsp)
      (add-hook 'rust-mode-hook #'lsp))

  (use-package lsp-ui
    :requires lsp-mode flycheck
    :config

    (setq lsp-ui-doc-enable nil
          lsp-ui-sideline-enable nil
          lsp-ui-flycheck-enable t
          lsp-ui-flycheck-list-position 'right
          lsp-ui-flycheck-live-reporting t)

    (add-hook 'lsp-mode-hook 'lsp-ui-mode))
#+END_SRC

** CMake
#+BEGIN_SRC emacs-lisp
(use-package cmake-font-lock)
  (add-to-list 'load-path "~/config/emacs/cmake-mode")
  (setq cmake-tab-width 4)
#+END_SRC
** Compile mode
When compiling, jump to the first error in the compile output.
#+BEGIN_SRC emacs-lisp
  (setq compilation-scroll-output 'first-error)
#+END_SRC
* Org
** General settings.

#+BEGIN_SRC emacs-lisp
  (setq org-startup-indented 'f)
  (setq org-directory "~/org")
  (setq org-special-ctrl-a/e 't)
  (setq org-default-notes-file (concat org-directory "/notes.org"))
  (setq org-src-fontify-natively 't)
  (setq org-src-tab-acts-natively t)
(define-key global-map "\C-cl" 'org-store-link)
(define-key global-map "\C-ca" 'org-agenda)
  (setq org-src-window-setup 'current-window)
#+END_SRC

Define a function to my global TODO list. Use =C-c T= to open the TODO file.

#+BEGIN_SRC emacs-lisp
  (defun find-todo ()
    "Edit todo.org"
    (interactive)
    (find-file "~/org/todo.org"))

  (global-set-key (kbd "C-c T") 'find-todo)
#+END_SRC

** Appearance

Improve the display of bullet points.

#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
    :config
    (setq org-bullets-bullet-list '("∙"))
    (add-hook 'org-mode-hook 'org-bullets-mode))
#+END_SRC

Customize appearance.

#+BEGIN_SRC emacs-lisp
  (let*
      ((variable-tuple (cond
                        ((x-list-fonts "Source Sans Pro") '(:font "Source Sans Pro"))
                        ((x-list-fonts "Lucida Grande")   '(:font "Lucida Grande"))
                        ((x-list-fonts "Verdana")         '(:font "Verdana"))
                        ((x-family-fonts "Sans Serif")    '(:family "Sans Serif"))
                        (nil (warn "Cannot find a Sans Serif Font.  Install Source Sans Pro."))))
       (base-font-color     (face-foreground 'default nil 'default))
       (headline           `(:inherit default :weight normal :foreground ,base-font-color)))

    (custom-theme-set-faces 'user
                            `(org-level-8 ((t (,@headline ,@variable-tuple))))
                            `(org-level-7 ((t (,@headline ,@variable-tuple))))
                            `(org-level-6 ((t (,@headline ,@variable-tuple))))
                            `(org-level-5 ((t (,@headline ,@variable-tuple))))
                            `(org-level-4 ((t (,@headline ,@variable-tuple))))
                            `(org-level-3 ((t (,@headline ,@variable-tuple :height 1.33))))
                            `(org-level-2 ((t (,@headline ,@variable-tuple :height 1.33))))
                            `(org-level-1 ((t (,@headline ,@variable-tuple :height 1.33 ))))
                            `(org-document-title ((t (,@headline ,@variable-tuple :height 1.33 :underline nil))))))
#+END_SRC

* PlantUML

PlantUML is used to generate UML from text descriptions. 
Expect the plantuml.jar file in the home directory.

#+BEGIN_SRC emacs-lisp
  (use-package plantuml-mode)
  ;; active Org-babel languages
  (org-babel-do-load-languages
   'org-babel-load-languages
   '(;; other Babel languages
     (plantuml . t)))
  (setq org-plantuml-jar-path
        (expand-file-name "~/plantuml.jar"))



  (add-hook 'org-babel-after-execute-hook
            (lambda ()
              (when org-inline-image-overlays
                (org-redisplay-inline-images))))

  (add-to-list 'auto-mode-alist '("\\.puml\\'" . plantuml-mode))
#+END_SRC
